### ISSUE TITLE
QBWC1048: QuickBooks Web Connector could not verify the web application server certificate

### ISSUE THREAD

**Issue by rchekaluk** [skryl/qbwc#30]
When running the qbwc gem behind https (here, on Heroku) and using an appropriate .qwc file to "Add an application", QuickBooks Web Connector first attempts to obtain and validate the certificate by hitting AppURL. Because this is not a SOAP request, gem qbwc crashes with this error:
```
2014-11-21T23:22:07.740648+00:00 app[web.1]: Started GET "/qbwc/action" for XXX.XXX.XXX.XXX at 2014-11-21 23:22:07 +0000
2014-11-21T23:22:07.744092+00:00 app[web.1]: 
2014-11-21T23:22:07.744095+00:00 app[web.1]: NoMethodError (undefined method `values_at' for nil:NilClass):
2014-11-21T23:22:07.744097+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/wash_out-0.9.0/lib/wash_out/router.rb:23:in `parse_soap_action'
2014-11-21T23:22:07.744099+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/wash_out-0.9.0/lib/wash_out/router.rb:72:in `call'
2014-11-21T23:22:07.744101+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
2014-11-21T23:22:07.744102+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
2014-11-21T23:22:07.744104+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
2014-11-21T23:22:07.744106+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
2014-11-21T23:22:07.744107+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
2014-11-21T23:22:07.744109+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
2014-11-21T23:22:07.744110+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
2014-11-21T23:22:07.744112+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/
middleware/params_parser.rb:27:in `call'
2014-11-21T23:22:07.744114+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254:in `call'
2014-11-21T23:22:07.744116+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
2014-11-21T23:22:07.744117+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
2014-11-21T23:22:07.744119+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
These are not in reproduced in test case
2014-11-21T23:22:07.744121+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'
2014-11-21T23:22:07.744123+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
2014-11-21T23:22:07.744124+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2014-11-21T23:22:07.744126+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'
2014-11-21T23:22:07.744127+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2014-11-21T23:22:07.744129+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
2014-11-21T23:22:07.744130+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2014-11-21T23:22:07.744132+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2014-11-21T23:22:07.744133+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'
2014-11-21T23:22:07.744135+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `block in call'
2014-11-21T23:22:07.744136+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2014-11-21T23:22:07.744138+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:26:in `tagged'
2014-11-21T23:22:07.744139+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `tagged'
2014-11-21T23:22:07.744141+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `call'
2014-11-21T23:22:07.744142+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
2014-11-21T23:22:07.744143+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2014-11-21T23:22:07.744145+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
2014-11-21T23:22:07.744146+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
2014-11-21T23:22:07.744148+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
2014-11-21T23:22:07.744150+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/static.rb:84:in `call'
2014-11-21T23:22:07.744151+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
2014-11-21T23:22:07.744153+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
2014-11-21T23:22:07.744154+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'
2014-11-21T23:22:07.744183+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
2014-11-21T23:22:07.744185+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
2014-11-21T23:22:07.744186+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
2014-11-21T23:22:07.744188+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
2014-11-21T23:22:07.744194+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
2014-11-21T23:22:07.744195+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
2014-11-21T23:22:07.744197+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
2014-11-21T23:22:07.744198+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
2014-11-21T23:22:07.744200+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
2014-11-21T23:22:07.744202+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
2014-11-21T23:22:07.744203+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
2014-11-21T23:22:07.744204+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
2014-11-21T23:22:07.744206+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/commands/server.rb:69:in `start'
2014-11-21T23:22:07.744207+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:81:in `block in server'
2014-11-21T23:22:07.744209+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `tap'
2014-11-21T23:22:07.744210+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `server'
2014-11-21T23:22:07.744211+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
2014-11-21T23:22:07.744213+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
2014-11-21T23:22:07.744215+00:00 app[web.1]:   bin/rails:8:in `require'
2014-11-21T23:22:07.744216+00:00 app[web.1]:   bin/rails:8:in `<main>'
```
And the QuickBooks Web Connector log contains this:
```
20141124.22:42:06 UTC	: QWCReader.ParseQWC() : Contents of QWC file: -
<QBWCXML>
  <AppDescription>REDACTED</AppDescription>
  <AppID></AppID>
  <AppName>REDACTED</AppName>
  <AppSupport>https://REDACTED.herokuapp.com/support</AppSupport>
  <AppURL>https://REDACTED.herokuapp.com/qbwc/action</AppURL>
  <OwnerID>REDACTED</OwnerID>
  <FileID>REDACTED</FileID>
  <Notify>true</Notify>
  <QBType>QBFS</QBType>
  <Scheduler>
    <RunEveryNMinutes>60</RunEveryNMinutes>
  </Scheduler>
  <UserName>REDACTED</UserName>
</QBWCXML>
20141124.22:42:06 UTC	: QBWebConnector.WebServiceManager.ReadQWC(QWCReader QWC) : Parsing application configuration xml file to load its content to variables
20141124.22:42:07 UTC	:  : QBWC1048: QuickBooks Web Connector could not verify the web application server certificate.

Certificate URL: https://REDACTED.herokuapp.com/qbwc/actionStackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at QBWebConnector.QWCReader.CheckCertURL()

Message (description of the exception):
The remote server returned an error: (500) Internal Server Error.

Source (name of application or object that caused the exception):
System

TargetSite (method that threw the exception):
System.Net.WebResponse GetResponse()

InnerException:

20141124.22:42:12 UTC	: QBWebConnector.WebServiceManager.ReadQWC(QWCReader QWC) : QBWC1048: QuickBooks Web Connector could not verify the web application server certificate.

QBWC1051: The new application was not added
```

**Comment by JasonBarnabe** [comment]
@rchekaluk have you got a fix for the failing test?

**Comment by rchekaluk** [comment]
Will be investigating soon.

**Comment by rchekaluk** [comment]
Can no longer reproduce.
