### ISSUE TITLE
Unable to use multiple IncludeRetElement

### ISSUE THREAD

**Issue by Rishka** [skryl/qbwc#39]
In order to reduce the amount of data being sent, I usually have qbmxl return just the elements I require
using IncludeRetElement tags. Is there a way to use multiple elements of the same name?
for example:
```xml
<IncludeRetElement>ListID</IncludeRetElement>
<IncludeRetElement>Name</IncludeRetElement>
```
Because it is a hash, I would assume you would have to do something like 
```ruby
 :include_ret_element => ['ListID', 'Name] 
```
Or is there a way to convert the hash to xml and add items in a specific spot.

**Comment by JasonBarnabe** [comment]
That looks to me like how you would do it. Does it not work?

**Comment by Rishka** [comment]
Sorry, I meant to mention that I tried it.
No, it gives: `ArgumentError (XmlMarkup cannot mix a text argument with a block):`

Here is the stack trace:
```
ArgumentError (XmlMarkup cannot mix a text argument with a block):
  builder (3.2.2) lib/builder/xmlbase.rb:61:in `tag!'
  qbxml (0.1.6) lib/qbxml/hash.rb:58:in `hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:64:in `block (3 levels) in hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:64:in `map'
  qbxml (0.1.6) lib/qbxml/hash.rb:64:in `block (2 levels) in hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:59:in `each'
  qbxml (0.1.6) lib/qbxml/hash.rb:59:in `block in hash_to_xml'
  builder (3.2.2) lib/builder/xmlbase.rb:175:in `call'
  builder (3.2.2) lib/builder/xmlbase.rb:175:in `_nested_structures'
  builder (3.2.2) lib/builder/xmlbase.rb:68:in `tag!'
  qbxml (0.1.6) lib/qbxml/hash.rb:58:in `hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:62:in `block (2 levels) in hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:59:in `each'
  qbxml (0.1.6) lib/qbxml/hash.rb:59:in `block in hash_to_xml'
  builder (3.2.2) lib/builder/xmlbase.rb:175:in `call'
  builder (3.2.2) lib/builder/xmlbase.rb:175:in `_nested_structures'
  builder (3.2.2) lib/builder/xmlbase.rb:68:in `tag!'
  qbxml (0.1.6) lib/qbxml/hash.rb:58:in `hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:62:in `block (2 levels) in hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:59:in `each'
  qbxml (0.1.6) lib/qbxml/hash.rb:59:in `block in hash_to_xml'
  builder (3.2.2) lib/builder/xmlbase.rb:175:in `call'
  builder (3.2.2) lib/builder/xmlbase.rb:175:in `_nested_structures'
  builder (3.2.2) lib/builder/xmlbase.rb:68:in `tag!'
  qbxml (0.1.6) lib/qbxml/hash.rb:58:in `hash_to_xml'
  qbxml (0.1.6) lib/qbxml/hash.rb:33:in `to_xml'
  qbxml (0.1.6) lib/qbxml/qbxml.rb:41:in `to_qbxml'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/qbwc-e199222ec3b5/lib/qbwc/request.rb:12:in `initialize'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/qbwc-e199222ec3b5/lib/qbwc/job.rb:81:in `new'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/qbwc-e199222ec3b5/lib/qbwc/job.rb:81:in `next'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/qbwc-e199222ec3b5/lib/qbwc/session.rb:32:in `next'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/qbwc-e199222ec3b5/lib/qbwc/session.rb:41:in `current_request'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/qbwc-e199222ec3b5/lib/qbwc/controller.rb:107:in `send_request'
  actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
  wash_out (0.9.0) lib/wash_out/router.rb:83:in `call'
  wash_out (0.9.0) lib/wash_out/router.rb:83:in `call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/a/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by JasonBarnabe** [comment]
Can you post your full code?

**Comment by Rishka** [comment]
Sure
/config/initializers/item_worker.rb
```ruby
require 'qbwc'

class ItemWorker < QBWC::Worker

  def requests
    {
      :item_inventory_query_rq => {
        :xml_attributes => { "requestID" =>"1", 'iterator'  => "Start" },
        :max_returned => 200,
        :from_modified_date => "2014-06-30",
#        :include_ret_element =>  'ListID',
        :include_ret_element => ['ListID', 'Name']

      }
    }
  end

  def should_run?
    true
  end

  def handle_response(r)
    # handle_response will get customers in groups of 100. When this is 0, we're done.
    complete = r['xml_attributes']['iteratorRemainingCount'] == '0'
    r['item_inventory_ret'].each do |qb_item|
      qb_id = qb_item['list_id']
      qb_name = qb_item['name']
      end
      Rails.logger.info("#{qb_id} #{qb_name}")
    end
  end

end
```
 I started a rails console and did:`QBWC.add_job(:list_items, true, '', ItemWorker)`

What other files do you need?

**Comment by JasonBarnabe** [comment]
That should be sufficient.

**Comment by JasonBarnabe** [comment]
I've filed https://github.com/skryl/qbxml/issues/11.

I'm unlikely to work on that unless I'm personally hit by it, but feel free to make a PR against that project.

**Comment by JasonBarnabe** [comment]
Closing as this related to the qbxml project.
