### ISSUE TITLE
Lots of (Rails 4.2?) errors and warnings running tests

### ISSUE THREAD

**Issue by JasonBarnabe** [skryl/qbwc#67]
```
jason@jason-X550CA:/www/qbwc$ rake test
-- create_table(:qbwc_jobs)
DEPRECATION WARNING: `#timestamp` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /www/qbwc/lib/generators/qbwc/install/templates/db/migrate/create_qbwc_jobs.rb:12)
   -> 0.0072s
-- create_table(:qbwc_sessions)
DEPRECATION WARNING: `#timestamp` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /www/qbwc/lib/generators/qbwc/install/templates/db/migrate/create_qbwc_sessions.rb:13)
   -> 0.0012s
Run options: --seed 43978

# Running:

DEPRECATION WARNING: You did not specify a value for the configuration option `active_support.test_order`. In Rails 5, the default value of this option will change from `:sorted` to `:random`.
To disable this warning and keep the current behavior, you can add the following line to your `config/environments/test.rb`:

  Rails.application.configure do
    config.active_support.test_order = :sorted
  end

Alternatively, you can opt into the future behavior by setting this option to `:random`. (called from test_order at /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/activesupport-4.2.0/lib/active_support/test_case.rb:42)
........DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate_wrong_password at /www/qbwc/test/test_helper.rb:238)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from block in <class:QBWCControllerTest> at /www/qbwc/test/qbwc/controllers/controller_test.rb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from qwc at /www/qbwc/lib/qbwc/controller.rb:77)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
.DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details. (called from _authenticate at /www/qbwc/test/test_helper.rb:218)
......................................EE

Finished in 2.410861s, 24.4726 runs/s, 124.4369 assertions/s.

  1) Error:
RoutesTest#test_qbwc/action_without_soap_returns_successfully:
URI::InvalidURIError: bad URI(is not URI?): http://www.example.com:80qbwc/action
    /home/jason/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
    /home/jason/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
    /home/jason/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/rack-test-0.6.3/lib/rack/test.rb:193:in `env_for'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/rack-test-0.6.3/lib/rack/test.rb:123:in `request'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/actionpack-4.2.0/lib/action_dispatch/testing/integration.rb:297:in `process'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/actionpack-4.2.0/lib/action_dispatch/testing/integration.rb:32:in `get'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/actionpack-4.2.0/lib/action_dispatch/testing/integration.rb:344:in `block (2 levels) in <module:Runner>'
    /www/qbwc/test/qbwc/integration/routes_test.rb:34:in `block in <class:RoutesTest>'


  2) Error:
RoutesTest#test_qwc:
URI::InvalidURIError: bad URI(is not URI?): http://www.example.com:80qbwc/qwc
    /home/jason/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
    /home/jason/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
    /home/jason/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/rack-test-0.6.3/lib/rack/test.rb:193:in `env_for'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/rack-test-0.6.3/lib/rack/test.rb:123:in `request'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/actionpack-4.2.0/lib/action_dispatch/testing/integration.rb:297:in `process'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/actionpack-4.2.0/lib/action_dispatch/testing/integration.rb:32:in `get'
    /home/jason/.rvm/gems/ruby-2.2.0@qbwc/gems/actionpack-4.2.0/lib/action_dispatch/testing/integration.rb:344:in `block (2 levels) in <module:Runner>'
    /www/qbwc/test/qbwc/integration/routes_test.rb:22:in `block in <class:RoutesTest>'

59 runs, 300 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib"  "/home/jason/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by JasonBarnabe** [comment]
`Rails.application.configure` seems to require Rails 4.1, so I'll make that the minimum development dependency.

**Comment by JasonBarnabe** [comment]
```
jason@jason-X550CA:/www/qbwc$ rake test
-- create_table(:qbwc_jobs, {:force=>true})
   -> 0.0082s
-- create_table(:qbwc_sessions, {:force=>true})
   -> 0.0011s
Run options: --seed 22264

# Running:

.............................................................

Finished in 2.395510s, 25.4643 runs/s, 134.4182 assertions/s.

61 runs, 322 assertions, 0 failures, 0 errors, 0 skips
```
